
version: '3.7'
services:
  postgres:
    container_name: project_db
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432' # 5438 internal / takhletelha bel localost ## 5432 external manakhltoulhesh bel external 
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  #streamlit:
    #depends_on: 
        #- postgres
    #build: .
    #ports:
      #- "8501:8501"
  #redis:
    #image: "debian:bullseye-slim"